### ISSUE TITLE
Default races.ini with spaces in Filename not optimal for Linux

### ISSUE THREAD

**Issue by PanadeEdu** [ManifestManah/Racepack-Standard#3]
I am currently trying to build an automatic build with this Project in it.
While it is not impossible, it is slightly annoying to always escape the space for the Racepack races.ini for a rename. 
Avoiding spaces in filenames would make it a lot easier (and less messy) to rename it. 

File in question:
 Racepack-Standard/cfg/source-python/wcs/Racepack Standard - (Version 1.0.10B).ini 
 
 Example what I need to do, to not get my script rattled up:
 Racepack\ Standard\ -\ \(Version\ 1.0.9B\).ini
 
 Proposed Fix:
 replaces spaces in filename with dashes or something :)

**Comment by PanadeEdu** [comment]
just for reference if anyone wants to put this in ansible, something like this works.
I first search the filename with a glob and then run a shell with the quoted variable so i avoid escaping it. 

Would still be way easier to simply have a non-whitespace filename :D 

```
# Get filename for Racepack ini first
- name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
  find:
    paths: "{{ csgoroot }}/serverfiles/csgo/cfg/source-python/wcs"
    patterns: "Racepack*.ini"
  register: racepackfind
# Rename racepack ini to autoload those races
# Important: single quote will avoid spaces breaking mv
- name: "Rename Racepack ini"
  shell: "mv '{{ racepackfind.files[0].path }}' {{ csgoroot }}/serverfiles/csgo/cfg/source-python/wcs/races.ini"
```
